---
title: "Homeworks"
output: html_document
---

# Coding

The due date is in the link. 

| Assigned | Labs | Assignments | In class exercises |
|----------|------|-------------|--------------------|
| January 12 | [data.gov](labs/1/gov_data.html) | | |
| January 17 |[reproducible data.gov](labs/2/reproducible_gov_data.html) | | [the command line](class_exercises/command_line/command_line.html)|
| January 19 |  | | |

# Reading
Readings should be complete by the following class period. r4ds = [R for Data Science](http://r4ds.had.co.nz/)

**January 12**

- read through the [getting started notes](https://idc9.github.io/stor390/notes/getting_started/getting_started.html)
- read [before we start](http://www.datacarpentry.org/R-ecology-lesson/00-before-we-start.html) from data carpentry
- sections 1, 2, 3.1-3.5 of r4ds
    - I suggest copying/pasting and running some of the example code
- [Data science done well looks easy - and that is a big problem for data scientists](http://simplystatistics.org/2015/03/17/data-science-done-well-looks-easy-and-that-is-a-big-problem-for-data-scientists/)
- This tutorial may be helpful for [getting started with R Markdown](http://stat545.com/block007_first-use-rmarkdown.html)

- (Optional) [For Big-Data Scientists, ‘Janitor Work’ Is Key Hurdle to Insights](https://www.nytimes.com/2014/08/18/technology/for-big-data-scientists-hurdle-to-insights-is-janitor-work.html) and [David Mimno's response](http://www.mimno.org/articles/carpentry/)
- [big data is like teenage sex](https://www.facebook.com/dan.ariely/posts/904383595868)


**January 17th**

- read sections 3.5 - 3.10 and section 8 from r4ds

