---
title: "STOR 390: Introduction to Data Science"
output: html_document
---

Instructor: [Iain Carmichael](http://iaincarmichael.web.unc.edu/)

- iain@unc.edu
- Hanes B30
- office hours: TBA

Grader: Brendan Brown

- bb@live.unc.edu
- Hanes 318
- office hours: TBA

Graduat Research Consultant: [Varun Goel](http://varungoel.web.unc.edu/author/varung/)

- varung@live.unc.edu
- OFFICE TODO
- office hours: TBA

# Prerequisites
Some coding or some statistics (STOR 155 or COMP 110)

# Textbook
We will follow [R for Data Science](http://r4ds.had.co.nz/) by Hadley Whickham (this is free online). I will provide additional resources in the lecture nodes.

Google is a programmer's best friend. There is a good chance any question you have has already been asked and answered on [StackOverflow](http://stackoverflow.com/).

# Technology
We will use the [R](https://www.r-project.org/about.html) programming language and [R Studio](https://www.rstudio.com/). Both of these are free. Students must have a laptop and bring it to class. If this is a problem please see the instructor.

# Grades
- Homework: 40%
    - 4 data analyses
- Labs: 30%
    - start these in class they are due the following class period
- Class participation: 15%
- Final project: 15%

Homeworks are graded on a 100 point scale. Homeworks will be graded on: statistical rigor, programming accuracy, and communication. Note that communication includes: writing human readable code, clear visualizations and coherent writing. Detailed rubrics will be provided with each assignment. 

Some of these homeworks will be done in teams (see below for group work policy). One homework may be dropped *if you participate in [DataFest](http://www2.stat.duke.edu/datafest/)*. 

Labs are graded on a 0-3 scale

- 0: not handed in
- 1: partially complete
- 2: complete with mistakes
- 3: complete (possibly minor mistakes)

Class activities will include discussing readings

Class activities will be graded on a 0-1 point scale (i.e. incomplete/complete). One missing class activity will be dropped. If you miss more than one you may make them up by doing an additional assignment of the instructor's choosing. Warning: the more classes you miss the more challenging these assignments will become.

The final project is to do a novel data analysis and write a blog post about it. This project will be done in groups. You are more than welcome to reach out to professional researchers and companies to collaborate for this project. See [HERE TODO]() for more details. 

# Group work
The teamwork policy comes from [Teaching and Learning STEM](http://www.wiley.com/WileyCDA/WileyTitle/productCd-1118925815.html) and applies to homeworks and the final project (not class activities).

- the instructor will assign teams
- final grade will be adjusted by peer ratings
- as a last resort a team may fire an uncooperative member

More details will be provided before the first team project.

# Plagiarism

For labs/group activities you are encouraged to work with other people, however, you are **not allowed to copy someone else's code**. For homeworks youare encouraged to use online resources as long as you **cite a resource you borrow code from**. 


# Getting help from the instructional staff
Programming can be incredibly frustrating and take some time to get used to. Before you email the TA please spend some time trying to solve/Google the problem. Once you have exhausted your resources/patience ask some (rule of thumb: don't spend more than 20 minutes stuck on one problem).
