---
title: "Extra resources"
author: "STOR 390"
output: html_document
---

This is a collection of resources for learning R/data science. If you have feedback feel free to email Iain.

# Learn R

- [R for Data Science](http://r4ds.had.co.nz/) by Hadley Wickham

- [r-bloggers](https://www.r-bloggers.com/)

- [Stack Overflow](http://stackoverflow.com/)
- [chrisalbon.com](http://chrisalbon.com/) has lots of reproducible examples

- [R Programming for Data Science](https://leanpub.com/rprogramming),  [Exploratory Data Analysis with R](https://leanpub.com/exdata), and [Report Writing for Data Science in R](https://leanpub.com/reportwriting) by Roger Peng

- [Computational and Inferential Thinking](http://www.inferentialthinking.com/index.html) Berkeley's data8 textbook

- [Coursera's Data Science specialization](https://www.coursera.org/specializations/jhu-data-science) by the guys at JHU

- [how to learn R](https://www.r-bloggers.com/how-to-learn-r-2/)

- [Kagge](https://www.kaggle.com/wiki/Tutorials) has a good list of R/data science tutorials

- [Swirl](http://swirlstats.com/) is an interactive intro do R

- [code school](https://www.codeschool.com/courses/try-r) is too

# Advanced R

- [Advanced R](http://adv-r.had.co.nz/) by Hadley Wickham

- Karl Broman's [Tools for Reproducible Research](http://kbroman.org/Tools4RR/pages/resources.html) is an amazing meta-resource 


# Statistics/machine learning textbooks

- [Introduction to Statitical Learing with R](http://www-bcf.usc.edu/~gareth/ISL/)

# Other data science courses

- [Stat 545](http://stat545.com/index.html) taught by Jenny Bryan at UBC

- [CS109: Data Science](http://cs109.github.io/2015/) by Joe Blitzstein at Harvard

- [BIO 260: Intoduction to Data Science](http://datasciencelabs.github.io/) by Rafael Irizarry and Stephanie Hicks at Harvard

- [Introduction to Data Analysis](http://stat405.had.co.nz/) by Hadley Whickham at Rice

- [Foundations of Data Science](https://data-8.appspot.com/sp16/course) at Berkeley 

- [JOMC390: Data Driven Journalism](http://ryanthornburg.com/about-contact/my-classes/syllabus-data-driven-journalism-jomc-390/) by Ryan Thornburg

- [Advanced Data Science](http://jtleek.com/advdatasci/) by Jeff Leek


# Vizualization and communication

- [Data Visualization course](http://vissoc.co/index.html) by Kiran Healy

- [Edward Tufe](https://www.edwardtufte.com/tufte/)'s books 
    - [Beautiful Evidence](http://www.amazon.com/Beautiful-Evidence-Edward-R-Tufte/dp/1930824165)

- [Trees, maps and theorems](http://www.treesmapsandtheorems.com/)


# Blogs
- [Simply Statistics](http://simplystatistics.org/) 

- [Flowing data](http://flowingdata.com/) tons of data viz

- [FiveThirtyEight](http://fivethirtyeight.com/)

- [I quant NY](http://iquantny.tumblr.com/)

- [Andrew Gelman's blog](http://andrewgelman.com/)

