---
title: "Lab 1: data.gov"
output: html_document
---
**Due January 17th at 5pm.**

# Instructions
- do the reading from January 12th
- find and download one data set from [data.gov](https://www.data.gov/) as a .csv
- load it into R and find something interesting
- communicate your results in R Markdown
    - write 1 paragraph describing the data set and what makes your result interesting
    - make one plot
    - compute one statistic


# Deliverables
Name the R Markdown file  *first*_*last*_L1.Rmd (i.e. iain_carmichael_L1.Rmd). On Sakai submit

- the .Rmd file
- the .html file
- the data

# Hints
- do all of your analysis in an R script file then copy the code into an R Markdown document
- some of the data on data.gov may be messy (have missing values, not load properly, not tell you what the columns mean, etc)
    - either try cleaning the data set yourself
    - or find a cleaner data set 
- save the data set in the same folder as the .Rmd file
- there is lot's of example code in [chapter 3](http://r4ds.had.co.nz/data-visualisation.html) of r4ds.
- try copy/pasting some of the code from r4ds and make various plots using the data set you have downloaded
- simple histogram or scatter plot will probably suffice


