---
title: 'Lab: Strings'
output: html_document
---

*Add instructions about how to submit this information for automatic checking*

## Overview

Here you will practice a few of the tricks we learned for string manipulation on the book of short stories *Dubliners* by James Joyce. The full text is available through Project Gutenberg.

These are admittedly dumb things to do to a classic book. We will learn much more interesting things to do with text data later in the class.

## Deliverables

1. Extract the story *Araby* using positive look-aheads and look-behinds. You probably will want to remove the table of contents before you can use the structure of the text to extract that particular story.

2. How many words does the story contain? You can use the regular expression shortcut for words.

3. Locate all instances of the word 'bazaar.'

4. What is the average word length?

5. A madlibs-like task: Replace all instances of 'bazaar' with 'pirate ship.'

6. Extract all groups of consonants. For example, 'chanting' would return a vector of 'ch', 'nt', 'ng.' [Consonant clusters](https://en.wikipedia.org/wiki/Comparative_method_(linguistics)#Step_1.2C_assemble_potential_cognate_lists) are used in comparitive linguistics. 

You can do this in a few ways. Remember that you can negate groups of characters in regular expressions, matching everything except those characters. For help see the character class section of the help file \text{?regexp}. But in negating you might get more than you want, so be sure to negate everything except what you are looking for.

Consider y to be a consonant.

7. Extract sentences ending with exclamation points, excluding the exclamation points themselves. For this you will want to be aware that commas, apostrophes, spaces and maybe semicolons can appear in the middle of sentences. At least one sentence has an ellipsis, which you likely will need to handle in a special way: Placing an element inside curly brackets, inside the box brackets \text{[]} allows you to match it optionally.

You should use a single regular expression to handle all of this and return a single vector of output.
**BBnote: fix apostrophe issue here. for some reason \text{\\'} is not working here on the apostrophe**

8. Extract all words ending with 'ss.' The only tricky part is making sure the double-s is at the end of the word. 

Use the word boundary regular expression, \text{\\b}, which matches the end or the beginning of words. An example with double l

```{r, warning=FALSE}
library(stringr)
str_extract(c('the bellicose', 'hellebore', 'fell', "unwell", "and the llama", "began to smell"), "[a-z]+l{2}")
str_extract(c('the bellicose', 'hellebore', 'fell', "unwell", "and the llama", "began to smell"), "[a-z]+l{2}\\b")
str_extract(c('the bellicose', 'hellebore', 'fell', "unwell", "and the llama", "began to smell"), "\\bl{2}[a-z]+")
```

9. Calculate the proportion of words beginning with T (capital or lower case) that are the word 'the.' You only need to return the proportion, giving it as a single number between zero and one.
