---
title: "Predictive modeling"
author: "STOR 390"
output: slidy_presentation
---


# Capital Bikeshare

![[]](http://www.freetoursbyfoot.com/wp-content/uploads/2014/04/article_2010_1012_capitalbikeshare.jpg)

# Load the data
```{r, warning=FALSE, message=F}
library(tidyverse)
hour <- read_csv('https://raw.githubusercontent.com/idc9/stor390/master/data/bikes_2011.csv')
```




# Look at the data

```{r}
head(hour)
```


# rider counts
```{r}
ggplot(hour) +
    geom_histogram(aes(x=cnt))
```


# temp vs. count
```{r}
ggplot(hour) +
    geom_point(aes(x=temp, y=cnt))
```


# riders per hour

```{r}
ggplot(hour) +
    geom_point(aes(x=hr, y=cnt))
```


# Consider a smaller problem

```{r}
hour <- hour %>% 
    select(cnt, hr)
```





# mean trend curve
```{r}
hour %>% 
    group_by(hr) %>% 
    summarise(mean_cnt=mean(cnt)) %>% 
    ggplot() +
    geom_line(aes(x=hr, y=mean_cnt)) +
    geom_point(aes(x=hr, y=mean_cnt))
```




# Predictive modeling

- predict the number of riders based only on the time of day 

    - build a model mapping `hr` to `cnt`

# Linear regression

```{r}
ggplot(hour) +
    geom_point(aes(x=hr, y=cnt)) +
    geom_smooth(aes(x=hr, y=cnt), color='red', method=lm, se=FALSE)
```

