---
title: "R Markdown is awesome"
output: html_document
---
This is an example R Markdown file reproducing the code from the first lecture. Check out the movies.Rmd file to see how this document was generated

# Setup

Load some R libraries
```{r packages}
library(tidyverse)
```

Next load the data which I downloaded from [Mine's website](http://www2.stat.duke.edu/~mc301/data/movies.html)
```{r data}
movies <- read_csv('../data/movies.csv')
```


# Analysis
Some numerical summaries
```{r code}
# some summaries of the data
str(movies)
head(movies)
mean(movies$imdb_num_votes)
```

We won't use base R plotting (sorry [Jeff](http://simplystatistics.org/2016/02/11/why-i-dont-use-ggplot2/)))
```{r base}
# base R plotting
plot(movies$imdb_rating, movies$critics_score)
```

We will stick to ggplot
```{r ggplot}
# ggplot2
# the + should freak you out a little if you have used R before...
ggplot(data = movies) + geom_point(mapping = aes(x = imdb_rating, y = critics_score))

# you can put code after the + on the next line
ggplot(data=movies, aes(x=audience_score)) +
    geom_histogram()

# looks much better that way...
ggplot(data = movies) +
    geom_point(mapping = aes(x = imdb_rating, y = critics_score, color=mpaa_rating))
```