---
title: "Lab 10: effective visualizations"
author: "[STOR 390](https://idc9.github.io/stor390/)"
output:
  html_document:
    theme: cosmo
    toc: yes
    toc_float: yes
---

This lab asks you to think about effective visualizations by making one of your own and critiquing someone else's visualization. Before attempting this lab make sure you are familiar with the content of the [effective communication lecture](https://idc9.github.io/stor390/notes/communication/communication.html).

This lab is due Tuesday 4/18/17. Please hand in a .Rmd file (make sure it knits) and possibly accompanying data (the grader will be happier if you load data from a url...)

# Question 1: Make your own plot


**1a**:  Take any plot that you made earlier this semester (even one that I made in a lecture) and turn it into a plot for communication (include the original plot as well). 

Include the code for both the original and the new plot. [This lecture](https://idc9.github.io/stor390/notes/custom_viz/custom_viz.html) and the resources listed at the top might be helpful.

**1b**: Explicitly state the message of the plot and the design choices you made to create the plot. How do the choices you made follow the principles of communication from lecture?



# Question 2: Critique a bad plot

Link to a bad plot somone posted online and answer the following questions:

- What is the message of the plot?
- What is wrong with the plot?
- How would you improve the plot to better convey the message?

Any graphic you find is fine. [viz.wtf/](http://viz.wtf/) has many examples of bad visualizations to pick on.


# Bonus question
Find an example of profesional communication and analyze it using the principles discussed in the [effective communication lecture](https://idc9.github.io/stor390/notes/communication/communication.html). Discuss how it uses and/or does not use these princples. Are their design choices effective? How would you improve their design choices? Submit a one page write up.


For example check out this [pitch deck](https://www.twine.fm/blog/pitch-deck-used-to-raise-a-million/) used by a startup called twine.

You can hand this in anytime before the end of the semester for one extra credit point.





